name: Build Site

on:
  push:
    branches: [main]
    paths:
      - 'data/events.sqlite.gz'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install deps
      run: pip install -r requirements.txt
    - name: Decompress DB
      run: gunzip -kf data/events.sqlite.gz
    - name: Generate site
      run: python -m src.cli build-site
    - name: Upload pages artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: docs
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
