name: Deploy Site

on:
  push:
    branches: [main]
    paths:
      - 'docs/index.html'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
    - uses: actions/checkout@v4
    
    - name: Upload pages artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: docs
    
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
