name: ETL

on:
  schedule:
    - cron:  '0 7 * * *'   # 07:00 UTC daily
  workflow_dispatch:

jobs:
  run-etl:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # for committing changes
      models: read # for accessing Github models
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    
    - name: Install uv
      uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57 # v8.0.0
    
    - name: Set up Python
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      with:
        python-version-file: "pyproject.toml"
    
    - name: Install the project
      run: uv sync --locked
    
    - name: Run ETL pipeline
      run: uv run seattle-volunteering pipeline
      env:
        GITHUB_TOKEN: ${{ github.token }}
    
    - name: Commit DB and site
      uses: EndBug/add-and-commit@290ea2c423ad77ca9c62ae0f5b224379612c0321 # v10.0.0
      with:
        add: 'data/events.sqlite.gz docs/index.html'
        message: 'chore(data): nightly DB and site update'
